#!/bin/bash
set -e
image_repo=${1:-"shevernts/test-app"}
image_tag=${2:-"0.0.1"}
DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME:? "Please xport DOCKER_HUB_USERNAME"}
DOCKER_HUB_PASSWORD=${DOCKER_HUB_PASSWORD:? "Please xport DOCKER_HUB_PASSWORD"}
BASEDIR=$(dirname "$0")
source "${BASEDIR}/time.sh"
echo "Building Docker Image.."
docker build -f Dockerfile -t ${image_repo}:${image_tag} .

docker login  -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD} ${image_repo}
docker push ${image_repo}:${image_tag}
docker logout ${image_repo}
echo "///////////////////////////////"
echo "Image:" ${image_repo}:${image_tag}
echo ""
echo "Image Build At:$(epoch)"
echo ""
echo "///////////////////////////////"

